Repository blw-ofag-ufag/data-catalog, pull requests merged in 2025-03, with the labels that each got.

#43 Fix ENUMS
  data/schemas/schema.json
Labels: schema

#48 Split schema (Closes #26)
  .gitignore
  data/schemas/catalog.json
  data/schemas/dataService.json
  data/schemas/dataset.json
  data/schemas/datasetSeries.json
  data/schemas/schema.json
Labels: schema

#56 Refactor site
  .gitignore
  docs/about.html
  docs/alternative/assets/js/details.js
  docs/alternative/assets/js/main.js
  docs/alternative/assets/js/translations.js
  docs/alternative/details.html
  docs/alternative/footer.html
  docs/alternative/index.html
  docs/assets/css/style.css
  docs/assets/js/details.js
  docs/assets/js/i18n.js
  docs/assets/js/main.js
  docs/assets/js/translations.js
  docs/assets/styles.css
  docs/assets/translations.json
  docs/details.html
  docs/footer.html
  docs/handbook.html
  docs/index.html
  docs/navbar.html
Labels: user interface

#61 Improvements on UI
  docs/assets/css/style.css
  docs/assets/js/details.js
  docs/assets/js/i18n.js
  docs/assets/js/main.js
  docs/assets/js/utils.js
  docs/details.html
  docs/index.html
  docs/navbar.html
Labels: user interface

#80 Update about.html
  docs/about.html
Labels: documentation, user interface

#84 Set up markdown files and move about.html content to about/de.md
  docs/about.html
  docs/assets/md/about/de.md
  docs/assets/md/about/en.md
  docs/assets/md/handbook/de.md
  docs/assets/md/handbook/en.md
  docs/handbook.html
  test/example.md
  test/index.html
Labels: enhancement

#85 Add mechanism to live-render markdown files
  docs/about.html
  docs/assets/js/markdown.js
  docs/assets/md/about/de.md
  docs/assets/md/about/en.md
  docs/assets/md/about/fr.md
  docs/assets/md/about/it.md
  docs/assets/md/handbook/fr.md
  docs/assets/md/handbook/it.md
  docs/assets/translations.json
  test/index.html
Labels: user interface, enhancement

#87 Changes in the about page (in German)
  docs/assets/md/about/de.md
Labels: documentation, user interface

#100 Add section about good (and bad) tagging
  docs/assets/md/handbook/de.md
  docs/assets/md/handbook/en.md
  docs/assets/md/handbook/fr.md
  docs/assets/md/handbook/it.md
Labels: documentation, user interface

#101 Translate about page to English, French, Italian
  docs/assets/md/about/en.md
  docs/assets/md/about/fr.md
  docs/assets/md/about/it.md
Labels: documentation, user interface

#103 Add function Utils.formatIdArray
  docs/assets/js/details.js
  docs/assets/js/utils.js
Labels: user interface

#102 Update README.md
  README.md
Labels: documentation, enhancement

#107 Add section on the metadata model
  docs/assets/md/handbook/de.md
  docs/assets/md/handbook/en.md
  docs/assets/md/handbook/fr.md
  docs/assets/md/handbook/it.md
Labels: user interface, schema

#108 Change the styling of mermaid charts
  docs/assets/css/style.css
  docs/assets/js/markdown.js
Labels: user interface

#111 Allow longer titles (two lines) in both tile and table view
  docs/assets/css/style.css
  docs/assets/js/main.js
  docs/assets/js/utils.js
Labels: user interface

#117 Hotfix: Move from unpgk to jsDelivr for the i18next script
  docs/about.html
  docs/details.html
  docs/index.html
Labels: bug
